package com.kpitracking.exception;

import org.springframework.http.HttpStatus;

/**
 * Mã lỗi gửi cho client trong {@code ApiResponse.code}. Tên enum CHÍNH LÀ mã: đã phát hành thì không đổi
 * tên, vì frontend dùng mã để quyết định logic (tải lại, chuyển trang, tô đỏ ô). Câu hiển thị nằm ở
 * {@code i18n/messages*.properties} với key {@code error.<MÃ>}.
 *
 * <p>Nhóm "theo loại exception" là mã cho lỗi chưa chuyển sang mã riêng: {@code new BusinessException("câu
 * tiếng Việt")} vẫn ra {@code BUSINESS_RULE} kèm câu nguyên văn. Lỗi mới thì thêm mã riêng ở đây và dùng
 * {@code new BusinessException(ErrorCode.X, args...)}. Thiết kế: {@code docs/I18N_DESIGN.md} §6.
 */
public enum ErrorCode {

    // ── Theo loại exception (message nguyên văn từ constructor cũ) ─────────────────────────
    BUSINESS_RULE(HttpStatus.UNPROCESSABLE_ENTITY),
    NOT_FOUND(HttpStatus.NOT_FOUND),
    FORBIDDEN(HttpStatus.FORBIDDEN),
    DUPLICATE_RESOURCE(HttpStatus.CONFLICT),
    STALE_STATE(HttpStatus.CONFLICT),
    ACCOUNT_LOCKED(HttpStatus.TOO_MANY_REQUESTS),
    AI_TOKEN_QUOTA_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS),
    AI_RATE_LIMITED(HttpStatus.TOO_MANY_REQUESTS),

    // ── Lỗi chung của tầng web / bảo mật ───────────────────────────────────────────────
    VALIDATION_FAILED(HttpStatus.BAD_REQUEST),
    BAD_REQUEST_PARAM(HttpStatus.BAD_REQUEST),
    FILE_TOO_LARGE(HttpStatus.BAD_REQUEST),
    UNAUTHORIZED(HttpStatus.UNAUTHORIZED),
    BAD_CREDENTIALS(HttpStatus.UNAUTHORIZED),
    AUTHENTICATION_FAILED(HttpStatus.UNAUTHORIZED),
    ACCESS_DENIED(HttpStatus.FORBIDDEN),
    CSRF_INVALID(HttpStatus.FORBIDDEN),
    CONCURRENT_UPDATE(HttpStatus.CONFLICT),
    RATE_LIMITED(HttpStatus.TOO_MANY_REQUESTS),
    AI_QUOTA_EXHAUSTED(HttpStatus.PAYMENT_REQUIRED),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),

    // ── Trùng dữ liệu (unique constraint) ──────────────────────────────────────────────
    DATA_CONFLICT(HttpStatus.CONFLICT),
    DUPLICATE_DATA(HttpStatus.CONFLICT),
    USER_EMAIL_EXISTS(HttpStatus.CONFLICT),
    EMAIL_EXISTS(HttpStatus.CONFLICT),
    EMPLOYEE_CODE_EXISTS(HttpStatus.CONFLICT),
    ORGANIZATION_NAME_EXISTS(HttpStatus.CONFLICT),
    ORGANIZATION_CODE_EXISTS(HttpStatus.CONFLICT),
    ORG_UNIT_CODE_EXISTS(HttpStatus.CONFLICT),
    ORG_UNIT_EMAIL_EXISTS(HttpStatus.CONFLICT),

    // ── Nghiệp vụ ──────────────────────────────────────────────────────────────────────
    UNSUPPORTED_LANGUAGE(HttpStatus.BAD_REQUEST),
    /** {0} tài nguyên (resource.*), {1} trường (field.* hoặc tên thô), {2} giá trị. */
    NOT_FOUND_BY_FIELD(HttpStatus.NOT_FOUND),
    DUPLICATE_BY_FIELD(HttpStatus.CONFLICT),
    /** {0} tài nguyên (resource.*). */
    RESOURCE_NOT_FOUND(HttpStatus.NOT_FOUND),
    INVALID_PAGE_CURSOR(HttpStatus.BAD_REQUEST),
    AVATAR_UPLOAD_FAILED(HttpStatus.UNPROCESSABLE_ENTITY),
    CANNOT_MODIFY_SYSTEM_ROLE_HIERARCHY(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_PERMISSION_DELETE_CONVERSATION(HttpStatus.FORBIDDEN),
    NO_PERMISSION_EDIT_CONVERSATION(HttpStatus.FORBIDDEN),

    // Workflow engine / HierarchyAuthorityGuard ({0} verb.*, {1} noun.*)
    STATUS_DOES_NOT_ALLOW_ACTION(HttpStatus.UNPROCESSABLE_ENTITY),
    ONLY_APPROVED_KPIS_CAN_REVERTED(HttpStatus.UNPROCESSABLE_ENTITY),
    SUBMISSION_STATUS_CANNOT_REVIEWED(HttpStatus.UNPROCESSABLE_ENTITY),
    GUARD_ACTOR_UNKNOWN(HttpStatus.FORBIDDEN),
    GUARD_NO_PERMISSION_IN_UNIT(HttpStatus.FORBIDDEN),
    GUARD_OWNER_HIGHER_LEVEL(HttpStatus.FORBIDDEN),
    GUARD_OWNER_SAME_POSITION(HttpStatus.FORBIDDEN),
    GUARD_NOT_SUPERIOR(HttpStatus.FORBIDDEN),

    // AiQuotaAllocationService
    QUOTA_CANNOT_NEGATIVE(HttpStatus.UNPROCESSABLE_ENTITY),
    PERSON_QUOTA_GRANTED_DIRECTLY_COMPANY_BUDGET(HttpStatus.UNPROCESSABLE_ENTITY),
    PERSON_QUOTA_GRANTED(HttpStatus.UNPROCESSABLE_ENTITY),
    CANNOT_SET_TOKENS(HttpStatus.UNPROCESSABLE_ENTITY),
    ONLY_TOP_LEVEL_MANAGER_CAN_TURN_SUBORDINATES(HttpStatus.FORBIDDEN),
    NO_PERMISSION_ALLOCATE_AI_TOKEN_QUOTAS(HttpStatus.FORBIDDEN),
    USER_OUTSIDE_UNIT(HttpStatus.UNPROCESSABLE_ENTITY),
    USER_OUTSIDE_ORGANIZATION(HttpStatus.FORBIDDEN),
    USER_OUTSIDE_MANAGEMENT_SCOPE(HttpStatus.FORBIDDEN),
    DO_NOT_BELONG_ORGANIZATION(HttpStatus.FORBIDDEN),

    // AiService
    AI_FEATURE_TURNED_OFF_ORGANIZATION(HttpStatus.FORBIDDEN),

    // AttachmentPolicy
    NO_FILE_SELECTED_ATTACH(HttpStatus.UNPROCESSABLE_ENTITY),
    EACH_REPORT_CAN_MOST_ATTACHMENTS(HttpStatus.UNPROCESSABLE_ENTITY),
    FILE_EMPTY(HttpStatus.UNPROCESSABLE_ENTITY),
    FILE_EXCEEDING_PER_FILE_LIMIT(HttpStatus.UNPROCESSABLE_ENTITY),
    FILE_NOT_SUPPORTED(HttpStatus.UNPROCESSABLE_ENTITY),
    FILE_DECLARES_TYPE_DOES_NOT_MATCH_EXTENSION(HttpStatus.UNPROCESSABLE_ENTITY),
    CONTENT_FILE_NOT_REALLY(HttpStatus.UNPROCESSABLE_ENTITY),

    // AuthService
    ORGANIZATION_STRUCTURE_MUST_LEAST_2_LEVELS(HttpStatus.UNPROCESSABLE_ENTITY),
    COULD_NOT_INITIALIZE_ADMINISTRATOR_ROLE_ORGANIZATION(HttpStatus.UNPROCESSABLE_ENTITY),
    ACCOUNT_NOT_ACTIVATED(HttpStatus.UNPROCESSABLE_ENTITY),
    VERIFY_EMAIL_BEFORE_SIGNING(HttpStatus.UNPROCESSABLE_ENTITY),
    ENTER_CURRENT_PASSWORD(HttpStatus.UNPROCESSABLE_ENTITY),
    CURRENT_PASSWORD_INCORRECT(HttpStatus.UNPROCESSABLE_ENTITY),
    NEW_PASSWORD_MUST_NOT_SAME_OLD_PASSWORD(HttpStatus.UNPROCESSABLE_ENTITY),
    NEW_PASSWORD_CONFIRMATION_DO_NOT_MATCH(HttpStatus.UNPROCESSABLE_ENTITY),
    INVALID_PASSWORD_RESET_CODE(HttpStatus.UNPROCESSABLE_ENTITY),
    PASSWORD_RESET_CODE_EXPIRED(HttpStatus.UNPROCESSABLE_ENTITY),
    INVALID_VERIFICATION_CODE(HttpStatus.UNPROCESSABLE_ENTITY),
    VERIFICATION_CODE_EXPIRED(HttpStatus.UNPROCESSABLE_ENTITY),

    // BscAccessGuard
    COULD_NOT_IDENTIFY_CURRENT_USER_2(HttpStatus.UNPROCESSABLE_ENTITY),
    ONLY_BSC_ADMINISTRATORS_CAN_WORK_ORGANIZATION_WIDE(HttpStatus.UNPROCESSABLE_ENTITY),
    CAN_ONLY_WORK_SCORECARDS_UNITS_MANAGE(HttpStatus.UNPROCESSABLE_ENTITY),

    // BscCascadeService
    BSC_RESULTS_PERIOD_FINALIZED(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_BSC_RESULTS_PERIOD(HttpStatus.UNPROCESSABLE_ENTITY),
    BSC_RESULTS_COULD_NOT_COMPUTED(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_BSC_RESULTS_PERIOD_2(HttpStatus.UNPROCESSABLE_ENTITY),
    RESULTS_FINALIZED(HttpStatus.UNPROCESSABLE_ENTITY),
    RESULT_ROW_OUTSIDE_PERIOD_BEING_EDITED(HttpStatus.UNPROCESSABLE_ENTITY),
    KPI_TAKES_FIGURES_AUTOMATICALLY_KPIS(HttpStatus.UNPROCESSABLE_ENTITY),

    // BscKpiPlanService
    SCORECARD_NOT_LINKED_PERIOD(HttpStatus.UNPROCESSABLE_ENTITY),
    CHOSEN_UNIT_NO_PEOPLE_ASSIGN(HttpStatus.UNPROCESSABLE_ENTITY),
    BSC_KPI_MISSING_ITEM_ROOT_SCORECARD(HttpStatus.UNPROCESSABLE_ENTITY),
    SCORECARD_APPLIES_ORGANIZATION_WIDE_UNIT_RECEIVING_KPI(HttpStatus.UNPROCESSABLE_ENTITY),
    CHOSEN_UNIT_OUTSIDE_SCOPE_SCORECARD(HttpStatus.UNPROCESSABLE_ENTITY),
    CHOSEN_PERIOD_NOT_WITHIN_SCOPE_SCORECARD(HttpStatus.UNPROCESSABLE_ENTITY),
    PERIOD_SPLIT_TWICE_SAME_CREATION(HttpStatus.UNPROCESSABLE_ENTITY),
    PERIOD(HttpStatus.UNPROCESSABLE_ENTITY),
    TOTAL_TARGET_SPLIT_ACROSS_PERIODS(HttpStatus.UNPROCESSABLE_ENTITY),
    TOTAL_TARGET_SPLIT_ACROSS_PERIODS_WITH_PRIOR(HttpStatus.UNPROCESSABLE_ENTITY),

    // BscPolicyService
    RECOGNIZED_SCORE_CAP_MUST_GREATER_THAN_0(HttpStatus.UNPROCESSABLE_ENTITY),
    SHARE_BSC_LINKED_KPIS_MUST_BETWEEN_0(HttpStatus.UNPROCESSABLE_ENTITY),
    APPLY_CYCLE_PERIOD_NOT_BOTH(HttpStatus.UNPROCESSABLE_ENTITY),
    PERIOD_COVERED_POLICY(HttpStatus.UNPROCESSABLE_ENTITY),
    ORGANIZATION_DEFAULT_POLICY(HttpStatus.UNPROCESSABLE_ENTITY),
    CYCLE_OWN_POLICY(HttpStatus.UNPROCESSABLE_ENTITY),

    // BscResultService
    SCORE_OVERRIDE_REQUIRES_REASON(HttpStatus.UNPROCESSABLE_ENTITY),
    OVERRIDE_SCORE_CANNOT_NEGATIVE(HttpStatus.UNPROCESSABLE_ENTITY),

    // BscService
    CANNOT_REMOVE_KPIS_ASSIGNED_PARENT(HttpStatus.UNPROCESSABLE_ENTITY),
    CHOOSE_EVALUATION_CYCLE_SCORECARD_APPLIES(HttpStatus.UNPROCESSABLE_ENTITY),
    EVALUATION_CYCLE_OUTSIDE_ORGANIZATION(HttpStatus.UNPROCESSABLE_ENTITY),
    CHOOSE_LEAST_ONE_PERIOD_SCORECARD_APPLIES(HttpStatus.UNPROCESSABLE_ENTITY),
    KPI_PERIOD_OUTSIDE_ORGANIZATION(HttpStatus.UNPROCESSABLE_ENTITY),
    DEFAULT_SCORECARD_EXISTS_PERIOD(HttpStatus.CONFLICT),
    DEPARTMENT_SCORECARD_PERIOD(HttpStatus.CONFLICT),
    DEPARTMENT_OUTSIDE_ORGANIZATION(HttpStatus.UNPROCESSABLE_ENTITY),
    COMPANY_LEVEL_SCORECARD_ROOT_BSC_TREE_CANNOT(HttpStatus.UNPROCESSABLE_ENTITY),
    SCORECARD_CANNOT_OWN_PARENT(HttpStatus.UNPROCESSABLE_ENTITY),
    PARENT_SCORECARD_MUST_BELONG_SAME_ORGANIZATION(HttpStatus.UNPROCESSABLE_ENTITY),
    PARENT_CHILD_LINK_CREATES_LOOP_BSC_TREE(HttpStatus.UNPROCESSABLE_ENTITY),
    GATE_ITEM_LIMITS_RATING_MUST_SPECIFY_CAP(HttpStatus.UNPROCESSABLE_ENTITY),
    TOTAL_WEIGHT_ITEMS_MUST_100_PERCENT(HttpStatus.UNPROCESSABLE_ENTITY),
    MUST_NUMBER(HttpStatus.UNPROCESSABLE_ENTITY),
    ONLY_2(HttpStatus.UNPROCESSABLE_ENTITY),
    EXCEL_FILE_EMPTY(HttpStatus.UNPROCESSABLE_ENTITY),
    MISSING_REQUIRED_COLUMNS(HttpStatus.UNPROCESSABLE_ENTITY),
    MISSING_PERIOD(HttpStatus.UNPROCESSABLE_ENTITY),
    MISSING_PERSPECTIVECODE(HttpStatus.UNPROCESSABLE_ENTITY),
    MISSING_WEIGHT(HttpStatus.UNPROCESSABLE_ENTITY),
    WEIGHT_MUST_NUMBER(HttpStatus.UNPROCESSABLE_ENTITY),
    ITEM_CODE_DUPLICATED_CYCLE(HttpStatus.UNPROCESSABLE_ENTITY),
    ERROR_READING_EXCEL_FILE(HttpStatus.UNPROCESSABLE_ENTITY),
    MISSING_SCORECARDNAME(HttpStatus.UNPROCESSABLE_ENTITY),
    TOTAL_WEIGHT_MUST_100_PERCENT(HttpStatus.UNPROCESSABLE_ENTITY),
    CYCLE_NOT_FOUND(HttpStatus.UNPROCESSABLE_ENTITY),
    CHOSEN_DEPARTMENTS_BELONG_SEVERAL_DIFFERENT_SCORECARDS_CYCLE(HttpStatus.UNPROCESSABLE_ENTITY),
    AREA_ITEM_INVALID(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_ITEM_CODE(HttpStatus.UNPROCESSABLE_ENTITY),
    ITEM_CODE_MAY_ONLY_CONTAIN_LETTERS_DIGITS(HttpStatus.UNPROCESSABLE_ENTITY),
    CODE_MATCHES_FIXED_AREA_CODE(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_DEPARTMENT_FOUND_CODE(HttpStatus.UNPROCESSABLE_ENTITY),
    ITEM(HttpStatus.UNPROCESSABLE_ENTITY),
    ITEM_2(HttpStatus.UNPROCESSABLE_ENTITY),
    ITEM_3(HttpStatus.UNPROCESSABLE_ENTITY),
    ITEM_4(HttpStatus.UNPROCESSABLE_ENTITY),
    ITEM_5(HttpStatus.UNPROCESSABLE_ENTITY),
    ITEM_6(HttpStatus.UNPROCESSABLE_ENTITY),
    ITEM_CODE_CANNOT_MATCH_FIXED_AREA_CODE(HttpStatus.UNPROCESSABLE_ENTITY),

    // BscTreeService
    SCORECARD_LOCKED(HttpStatus.UNPROCESSABLE_ENTITY),
    KPI_OUTSIDE_SCORECARD_BEING_CASCADED(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_UNIT_CHOSEN_CASCADE(HttpStatus.UNPROCESSABLE_ENTITY),
    KPIS_CAN_ONLY_ASSIGNED_DOWN_LOWER_UNITS(HttpStatus.UNPROCESSABLE_ENTITY),
    SCORECARD_CANNOT_ATTACHED_ITSELF(HttpStatus.UNPROCESSABLE_ENTITY),
    PARENT_SCORECARD_MUST_BELONG_SAME_ORGANIZATION_2(HttpStatus.UNPROCESSABLE_ENTITY),
    PARENT_SCORECARD_UNDER_VERY_SCORECARD(HttpStatus.UNPROCESSABLE_ENTITY),
    ONLY_DRAFT_SCORECARDS_CAN_SUBMITTED(HttpStatus.UNPROCESSABLE_ENTITY),
    SCORECARD_NO_KPIS(HttpStatus.UNPROCESSABLE_ENTITY),
    TOTAL_WEIGHT_MUST_100_PERCENT_SUBMIT(HttpStatus.UNPROCESSABLE_ENTITY),
    ONLY_SCORECARDS_PENDING_APPROVAL_CAN_APPROVED(HttpStatus.UNPROCESSABLE_ENTITY),
    ENTER_REASON_RETURNING(HttpStatus.UNPROCESSABLE_ENTITY),
    ONLY_SCORECARDS_PENDING_APPROVAL_CAN_RETURNED(HttpStatus.UNPROCESSABLE_ENTITY),
    ONLY_APPROVED_CLOSED_SCORECARDS_CAN_APPLIED(HttpStatus.UNPROCESSABLE_ENTITY),
    SCORECARD_NOT_APPROVED_CANNOT_LOCKED(HttpStatus.UNPROCESSABLE_ENTITY),
    SCORECARD_NOT_LOCKED(HttpStatus.UNPROCESSABLE_ENTITY),

    // CashQueryService
    MAXIMUM_TOP_UP_AMOUNT_MUST_GREATER_THAN(HttpStatus.UNPROCESSABLE_ENTITY),
    RECEIPTS_PREFIX_ISSUED_YEAR_PREFIX_CANNOT_CHANGED(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_PERMISSION_VIEW_EMPLOYEE_WALLET(HttpStatus.FORBIDDEN),

    // CashWalletService
    INSUFFICIENT_WALLET_BALANCE(HttpStatus.UNPROCESSABLE_ENTITY),

    // ConductService
    DEFAULT_SET_CANNOT_DELETED(HttpStatus.UNPROCESSABLE_ENTITY),
    CRITERIA_SET_OUTSIDE_ORGANIZATION(HttpStatus.FORBIDDEN),
    CRITERIA_SET_NAME_CANNOT_EMPTY(HttpStatus.UNPROCESSABLE_ENTITY),
    CRITERIA_SET_NAMED_EXISTS(HttpStatus.UNPROCESSABLE_ENTITY),
    SET_NEEDS_LEAST_ONE_CRITERION(HttpStatus.UNPROCESSABLE_ENTITY),
    TOTAL_WEIGHT_SET_MUST_100_PERCENT(HttpStatus.UNPROCESSABLE_ENTITY),
    DEFAULT_SET_APPLIES_EVERY_UNASSIGNED_CYCLE(HttpStatus.UNPROCESSABLE_ENTITY),
    CYCLE_OUTSIDE_ORGANIZATION(HttpStatus.FORBIDDEN),
    NO_PERMISSION_VIEW_PERSON_CONDUCT_FORM(HttpStatus.FORBIDDEN),
    ONLY_PERSON_THEMSELVES_MAY_FILL_SELF_ASSESSMENT(HttpStatus.FORBIDDEN),
    MISSING_PERSON_SCORE_CONDUCT(HttpStatus.UNPROCESSABLE_ENTITY),
    ONLY_UNIT_HEAD_MAY_SCORE_CONDUCT_PERSON(HttpStatus.FORBIDDEN),
    NO_PERMISSION_VIEW_UNIT_CONDUCT(HttpStatus.FORBIDDEN),
    MISSING_EVALUATION_PERIOD(HttpStatus.UNPROCESSABLE_ENTITY),
    MISSING_EVALUATION_CYCLE(HttpStatus.UNPROCESSABLE_ENTITY),
    ORGANIZATION_NOT_ENABLED_CONDUCT_SCORING(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_CONDUCT_CRITERIA_SET_CONFIGURED_CYCLE(HttpStatus.UNPROCESSABLE_ENTITY),
    SCORE_CRITERION_MUST_BETWEEN(HttpStatus.UNPROCESSABLE_ENTITY),
    CYCLE_EVALUATION_UNIT_FINALIZED_CONDUCT_CANNOT_SCORED(HttpStatus.UNPROCESSABLE_ENTITY),

    // ConversationService
    CONVERSATION_NAME_CANNOT_EMPTY(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_PERMISSION_VIEW_CONVERSATION(HttpStatus.FORBIDDEN),

    // CycleFinalizeTool
    NO_PERMISSION_SEND_EVALUATION_PERIOD_RESULTS(HttpStatus.FORBIDDEN),

    // CycleStatusGuard
    PERIOD_CLOSED_WHEN_CYCLE_LOCKED(HttpStatus.UNPROCESSABLE_ENTITY),
    KPI_CLOSED_CYCLE_LOCK(HttpStatus.UNPROCESSABLE_ENTITY),
    CYCLE_LOCKED(HttpStatus.UNPROCESSABLE_ENTITY),

    // DashboardLayoutService
    LAYOUT_MUST_JSON_ARRAY(HttpStatus.UNPROCESSABLE_ENTITY),
    LAYOUT_NOT_VALID_JSON(HttpStatus.UNPROCESSABLE_ENTITY),

    // DatasourceService
    USER_MUST_BELONG_LEAST_ONE_UNIT(HttpStatus.UNPROCESSABLE_ENTITY),
    DATA_SOURCE_CANNOT_DELETED_BECAUSE_CONNECTED_REPORT(HttpStatus.UNPROCESSABLE_ENTITY),

    // EvaluationService
    ORGANIZATION_TURNED_OFF_SELF_ASSESSMENT_STEP_KPI(HttpStatus.UNPROCESSABLE_ENTITY),
    ORGANIZATION_TURNED_OFF_EMPLOYEE_EVALUATION_STEP_KPI(HttpStatus.UNPROCESSABLE_ENTITY),
    USER_NOT_ASSIGNED_UNIT(HttpStatus.UNPROCESSABLE_ENTITY),
    CYCLE_FINALIZED_DATA_UNIT(HttpStatus.UNPROCESSABLE_ENTITY),
    SCORE_CANNOT_EXCEED(HttpStatus.UNPROCESSABLE_ENTITY),
    SCORE_CANNOT_EXCEED_WITH_BONUS(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_PERMISSION_CREATE_EVALUATIONS_OTHER_PEOPLE(HttpStatus.FORBIDDEN),
    ONLY_HEADS_MAY_EVALUATE_EMPLOYEES(HttpStatus.FORBIDDEN),
    MAY_ONLY_EVALUATE_EMPLOYEES_BELOW_ORGANIZATION_CHART(HttpStatus.FORBIDDEN),
    CANNOT_FINALIZE_EVALUATION(HttpStatus.UNPROCESSABLE_ENTITY),
    CANNOT_FINALIZE_EVALUATION_2(HttpStatus.UNPROCESSABLE_ENTITY),

    // EvidenceAttachmentService
    ONLY_UPLOADER_CAN_DELETE_EVIDENCE_FILE(HttpStatus.FORBIDDEN),
    INVALID_EVIDENCE_KEY(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_PERMISSION_VIEW_EVIDENCE_SCORING(HttpStatus.FORBIDDEN),

    // F360AccessPolicy
    DO_NOT_BELONG_ORGANIZATION_2(HttpStatus.FORBIDDEN),
    ORGANIZATION_NOT_ENABLED_F360_FEEDBACK(HttpStatus.FORBIDDEN),
    NO_PERMISSION_ADMINISTER_F360_FEEDBACK(HttpStatus.FORBIDDEN),
    F360_REPORT_NOT_PUBLISHED(HttpStatus.FORBIDDEN),
    CAMPAIGN_NOT_CLOSED_NO_RESULTS(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_PERMISSION_VIEW_F360_REPORT(HttpStatus.FORBIDDEN),
    CANNOT_PERFORM_ACTION_OWN_F360_FEEDBACK(HttpStatus.FORBIDDEN),

    // F360AnalyticsService
    NO_PERMISSION_VIEW_F360_CAMPAIGNS(HttpStatus.FORBIDDEN),
    CAMPAIGN_NOT_CLOSED_NO_RESULTS_EXPORT(HttpStatus.UNPROCESSABLE_ENTITY),

    // F360CampaignService
    CAMPAIGN_NO_QUESTIONS(HttpStatus.UNPROCESSABLE_ENTITY),
    CAMPAIGN_CLOSED_CONFIGURATION_CANNOT_EDITED(HttpStatus.UNPROCESSABLE_ENTITY),
    ONLY_DRAFT_CAMPAIGNS_CAN_DELETED(HttpStatus.UNPROCESSABLE_ENTITY),
    ORGANIZATION_NOT_ALLOWED_F360_COUNT_TOWARD_CYCLE(HttpStatus.UNPROCESSABLE_ENTITY),
    TOTAL_WEIGHT_GROUPS(HttpStatus.UNPROCESSABLE_ENTITY),
    EVALUATION_DEADLINE_MUST_FUTURE(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_ONE_SELECTED(HttpStatus.UNPROCESSABLE_ENTITY),
    EVERYONE_SELECTED_CAMPAIGN_INVALID(HttpStatus.UNPROCESSABLE_ENTITY),
    CAMPAIGN_NO_REVIEWEES(HttpStatus.UNPROCESSABLE_ENTITY),
    RATER_OUTSIDE_ORGANIZATION_ACCOUNT_LOCKED(HttpStatus.UNPROCESSABLE_ENTITY),
    SELF_ASSESSMENT_RELATIONSHIP_ONLY_REVIEWEE_THEMSELVES(HttpStatus.UNPROCESSABLE_ENTITY),
    RATER_PERSON(HttpStatus.UNPROCESSABLE_ENTITY),
    SUBMITTED_FORM_CANNOT_REMOVED(HttpStatus.UNPROCESSABLE_ENTITY),
    ONLY_SUBMITTED_FORMS_CAN_REOPENED(HttpStatus.UNPROCESSABLE_ENTITY),
    FORM_ANONYMIZED_CANNOT_REOPENED(HttpStatus.UNPROCESSABLE_ENTITY),
    SET_EVALUATION_DEADLINE_FUTURE_BEFORE_STARTING(HttpStatus.UNPROCESSABLE_ENTITY),
    CAMPAIGN_QUESTION_SET_DELETED(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_RATERS_BESIDES_SELF_ASSESSMENT(HttpStatus.UNPROCESSABLE_ENTITY),
    NOMINATION_DEADLINE_MUST_BEFORE_EVALUATION_DEADLINE(HttpStatus.UNPROCESSABLE_ENTITY),
    EVALUATION_DEADLINE_PASSED(HttpStatus.UNPROCESSABLE_ENTITY),
    ORGANIZATION_NOT_ALLOWED_F360_COUNT_TOWARD_CYCLE_2(HttpStatus.UNPROCESSABLE_ENTITY),
    CAMPAIGN_COUNTS_TOWARD_RATING_MUST_LINKED_KPI(HttpStatus.UNPROCESSABLE_ENTITY),
    CAMPAIGN_COUNTS_TOWARD_RATING_MUST_USE_1(HttpStatus.UNPROCESSABLE_ENTITY),
    CYCLE_F360_CAMPAIGN_COUNTS_TOWARD_RATING(HttpStatus.UNPROCESSABLE_ENTITY),
    QUESTION_SET_NO_SCORED_QUESTIONS(HttpStatus.UNPROCESSABLE_ENTITY),
    CAMPAIGN_NOT_CLOSED_AI_SUMMARY_NOT_ENABLED(HttpStatus.UNPROCESSABLE_ENTITY),
    CHOOSE_NEW_DEADLINE_WHEN_REOPENING_CAMPAIGN(HttpStatus.UNPROCESSABLE_ENTITY),
    CANNOT_WHILE_CAMPAIGN_STATUS(HttpStatus.UNPROCESSABLE_ENTITY),

    // F360CycleGuard
    CLOSE_F360_CAMPAIGN_BEFORE_FINALIZING_CYCLE_DATA(HttpStatus.UNPROCESSABLE_ENTITY),
    FOLLOWING_UNITS_FINALIZED_CYCLE_DATA_F360_CANNOT(HttpStatus.UNPROCESSABLE_ENTITY),

    // F360NominationService
    CAN_ONLY_NOMINATE_YOURSELF(HttpStatus.FORBIDDEN),
    RATER_LIST_APPROVED(HttpStatus.UNPROCESSABLE_ENTITY),
    CAN_NOMINATE_MOST_PEOPLE(HttpStatus.UNPROCESSABLE_ENTITY),
    NOMINEE_OUTSIDE_ORGANIZATION_LEFT(HttpStatus.UNPROCESSABLE_ENTITY),
    NOT_NOMINATION_APPROVER_PERSON(HttpStatus.FORBIDDEN),
    SELF_ASSESSMENT_CANNOT_REMOVED(HttpStatus.UNPROCESSABLE_ENTITY),
    ADDED_RATER_INVALID(HttpStatus.UNPROCESSABLE_ENTITY),
    RATER_OUTSIDE_ORGANIZATION_LEFT(HttpStatus.UNPROCESSABLE_ENTITY),
    CAMPAIGN_NO_LONGER_NOMINATION_PHASE(HttpStatus.FORBIDDEN),

    // F360ReportService
    ANSWER_NO_COMMENT(HttpStatus.UNPROCESSABLE_ENTITY),

    // F360ResponseService
    REQUIRED_QUESTIONS_UNANSWERED(HttpStatus.UNPROCESSABLE_ENTITY),
    SELF_ASSESSMENT_CANNOT_DECLINED(HttpStatus.UNPROCESSABLE_ENTITY),
    FORM_NO_LONGER_VALID(HttpStatus.FORBIDDEN),
    CAMPAIGN_CLOSED_FORM_CANNOT_EDITED(HttpStatus.UNPROCESSABLE_ENTITY),
    FORM_SUBMITTED_CANNOT_EDITED(HttpStatus.UNPROCESSABLE_ENTITY),
    FORM_NO_LONGER_OPEN_EDITING(HttpStatus.UNPROCESSABLE_ENTITY),
    QUESTION_OUTSIDE_FORM(HttpStatus.UNPROCESSABLE_ENTITY),
    QUESTION_DOES_NOT_ALLOW_CHOOSING_CANNOT_ASSESS(HttpStatus.UNPROCESSABLE_ENTITY),
    SCORE_MUST_INTEGER_1(HttpStatus.UNPROCESSABLE_ENTITY),
    COMMENTS_CAN_MOST_CHARACTERS(HttpStatus.UNPROCESSABLE_ENTITY),

    // F360Schedule
    START_DATE_MUST_BEFORE_EVALUATION_DEADLINE(HttpStatus.UNPROCESSABLE_ENTITY),
    START_DATE_MUST_WITHIN_CYCLE(HttpStatus.UNPROCESSABLE_ENTITY),
    CAMPAIGN_COUNTS_TOWARD_RATING_MUST_END_BEFORE(HttpStatus.UNPROCESSABLE_ENTITY),
    DEVELOPMENT_ONLY_CAMPAIGN_MUST_END_WITHIN_CYCLE(HttpStatus.UNPROCESSABLE_ENTITY),

    // F360TemplateService
    QUESTION_SET_NEEDS_LEAST_ONE_COMPETENCY(HttpStatus.UNPROCESSABLE_ENTITY),
    TOTAL_COMPETENCY_WEIGHT_MUST_100_PERCENT(HttpStatus.UNPROCESSABLE_ENTITY),
    COMPETENCY_NO_QUESTIONS(HttpStatus.UNPROCESSABLE_ENTITY),

    // KpiAdjustmentService
    NOT_ASSIGNED_KPI_CANNOT_REQUEST_ADJUSTMENT(HttpStatus.FORBIDDEN),
    ORGANIZATION_TURNED_OFF_ADJUSTMENT_REQUEST_STEP_KPI(HttpStatus.UNPROCESSABLE_ENTITY),
    REQUEST_HANDLED(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_PERMISSION_APPROVE_ADJUSTMENT_REQUESTS(HttpStatus.FORBIDDEN),
    NO_PERMISSION_APPROVE_ADJUSTMENT_REQUESTS_KPI(HttpStatus.FORBIDDEN),
    CANNOT_APPROVE_REQUESTS_SOMEONE_HIGHER_POSITION_THAN(HttpStatus.FORBIDDEN),
    CANNOT_APPROVE_REQUESTS_SOMEONE_SAME_POSITION(HttpStatus.FORBIDDEN),
    ENTER_ACHIEVEMENT_COMPENSATION_PERCENT_WHEN_APPROVING_REQUEST(HttpStatus.UNPROCESSABLE_ENTITY),
    ACHIEVEMENT_COMPENSATION_PERCENT_MUST_BETWEEN_0_150(HttpStatus.UNPROCESSABLE_ENTITY),
    ONLY_APPROVE_REJECT_DECISIONS_ACCEPTED(HttpStatus.UNPROCESSABLE_ENTITY),

    // KpiApprovalChainService
    NO_APPROVER_FOUND(HttpStatus.UNPROCESSABLE_ENTITY),
    APPROVAL_CHAIN_JUST_UPDATED_SOMEONE_ELSE_RELOAD(HttpStatus.CONFLICT),
    APPROVAL_CHAIN_NO_LONGER_EXISTS_RELOAD(HttpStatus.CONFLICT),
    APPROVAL_REQUEST_COMPLETED_RELOAD(HttpStatus.CONFLICT),
    APPROVAL_CHAIN_CHANGING_RELOAD(HttpStatus.CONFLICT),
    APPROVAL_STEP_CHANGED(HttpStatus.CONFLICT),
    ADMINISTRATORS_MAY_ONLY_REASSIGN_APPROVER_NOT_APPROVE(HttpStatus.FORBIDDEN),
    NOT_HOLDER_APPROVAL_STEP(HttpStatus.FORBIDDEN),
    CANNOT_APPROVE_OWN_REQUEST(HttpStatus.FORBIDDEN),
    ENTER_REJECTION_REASON(HttpStatus.UNPROCESSABLE_ENTITY),
    ONLY_ORGANIZATION_ADMINISTRATORS_MAY_REASSIGN_APPROVER(HttpStatus.FORBIDDEN),
    STEP_NO_LONGER_PENDING_APPROVAL_RELOAD(HttpStatus.CONFLICT),
    CHOSEN_PERSON_LEFT_DEACTIVATED(HttpStatus.UNPROCESSABLE_ENTITY),
    CHOSEN_PERSON_OUTSIDE_ORGANIZATION(HttpStatus.UNPROCESSABLE_ENTITY),
    SUBMITTER_CANNOT_ASSIGNED_APPROVER_THEIR_OWN_REQUEST(HttpStatus.UNPROCESSABLE_ENTITY),

    // KpiApprovalViewService
    NO_PERMISSION_VIEW_KPI_APPROVAL_HISTORY(HttpStatus.FORBIDDEN),

    // KpiCriteriaService
    ORGANIZATION_TURNED_OFF_KPI_APPROVAL_STEP_KPI(HttpStatus.UNPROCESSABLE_ENTITY),
    EVALUATION_FREQUENCY(HttpStatus.UNPROCESSABLE_ENTITY),
    USER_MUST_BELONG_LEAST_ONE_UNIT_CREATE(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_PERMISSION_CREATE_KPIS_UNIT(HttpStatus.FORBIDDEN),
    DEADLINE_CANNOT_BEFORE_START_DATE_EVALUATION_PERIOD(HttpStatus.UNPROCESSABLE_ENTITY),
    DEADLINE_CANNOT_AFTER_END_DATE_EVALUATION_PERIOD(HttpStatus.UNPROCESSABLE_ENTITY),
    QUALITATIVE_KPIS_NEED_WEIGHT_GREATER_THAN_0(HttpStatus.UNPROCESSABLE_ENTITY),
    CAN_ONLY_SPLIT_KPIS_CREATED_YOURSELF_ASSIGNED(HttpStatus.FORBIDDEN),
    TOTAL_WEIGHT_CHILD_KPIS(HttpStatus.UNPROCESSABLE_ENTITY),
    KPI_MUST_BELONG_SAME_UNIT_LINKED_KEY(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_PERMISSION_VIEW_KPI(HttpStatus.FORBIDDEN),
    NO_PERMISSION_EDIT_KPI(HttpStatus.FORBIDDEN),
    ONLY_MANAGERS_MAY_ADJUST_APPROVED_KPIS_WATERFALL(HttpStatus.UNPROCESSABLE_ENTITY),
    ONLY_KPIS_DRAFT_PENDING_APPROVAL_REJECTED_STATUS(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_PERMISSION_CREATE_MOVE_KPIS_NEW_UNIT(HttpStatus.FORBIDDEN),
    KPI_CANNOT_SUBMITTED_APPROVAL(HttpStatus.UNPROCESSABLE_ENTITY),
    TOTAL_WEIGHT_CHILD_KPIS_2(HttpStatus.UNPROCESSABLE_ENTITY),
    AFTER_SUBMITTING_UNIT_ONLY_REACHES_PERCENT_WEIGHT(HttpStatus.UNPROCESSABLE_ENTITY),
    UNIT_TOTAL_WEIGHT_HEADCOUNT_ALLOCATION(HttpStatus.UNPROCESSABLE_ENTITY),
    SELF_APPROVED_KPI_EXCEEDS_FULL_WEIGHT(HttpStatus.UNPROCESSABLE_ENTITY),
    APPROVED_KPI_EDIT_EXCEEDS_FULL_WEIGHT(HttpStatus.UNPROCESSABLE_ENTITY),
    APPROVED_KPI_WEIGHTS_EXCEED_FULL_WEIGHT(HttpStatus.UNPROCESSABLE_ENTITY),
    ONLY_KPIS_PENDING_APPROVAL_STATUS_CAN_APPROVED(HttpStatus.UNPROCESSABLE_ENTITY),
    INVERSE_KPI(HttpStatus.UNPROCESSABLE_ENTITY),
    KPI(HttpStatus.UNPROCESSABLE_ENTITY),
    CYCLE_USES_BSC_SCORECARD(HttpStatus.UNPROCESSABLE_ENTITY),
    CANNOT_APPROVE(HttpStatus.UNPROCESSABLE_ENTITY),
    ONLY_KPIS_PENDING_APPROVAL_STATUS_CAN_REJECTED(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_PERMISSION_DELETE_KPI(HttpStatus.FORBIDDEN),
    NO_PERMISSION_VIEW_USER_WEIGHT_INFORMATION(HttpStatus.FORBIDDEN),
    NO_PERMISSION_VIEW_UNIT_WEIGHT_INFORMATION(HttpStatus.FORBIDDEN),
    ONLY_3(HttpStatus.UNPROCESSABLE_ENTITY),
    EXCEL_FILE_EMPTY_2(HttpStatus.UNPROCESSABLE_ENTITY),
    REQUIRED_COLUMNS_MISSING_EXCEL_FILE(HttpStatus.UNPROCESSABLE_ENTITY),
    FILE_PROCESSING_ERROR(HttpStatus.UNPROCESSABLE_ENTITY),
    DATA_ERRORS_FILE_ROWS(HttpStatus.UNPROCESSABLE_ENTITY),
    IMPORT_ERROR(HttpStatus.UNPROCESSABLE_ENTITY),
    KPI_NAME_REQUIRED(HttpStatus.UNPROCESSABLE_ENTITY),
    WEIGHT_REQUIRED(HttpStatus.UNPROCESSABLE_ENTITY),
    TARGET_REQUIRED(HttpStatus.UNPROCESSABLE_ENTITY),
    CHOOSE_KPI_PERIOD_PROVIDE_PERIOD_NAME_EXCEL(HttpStatus.UNPROCESSABLE_ENTITY),
    CHOOSE_UNIT_PROVIDE_UNIT_NAME_EXCEL_FILE(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_EMPLOYEE_FOUND_CODE(HttpStatus.UNPROCESSABLE_ENTITY),
    PROVIDE_LEAST_ONE_EMPLOYEE_CODE_ASSIGN_KPI(HttpStatus.UNPROCESSABLE_ENTITY),
    FREQUENCY_INVALID(HttpStatus.UNPROCESSABLE_ENTITY),
    FREQUENCY_DOES_NOT_FIT_PERIOD_TYPE(HttpStatus.UNPROCESSABLE_ENTITY),
    WEIGHT_TARGET_MUST_NUMBERS(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_PERMISSION_CREATE_KPIS_UNIT_2(HttpStatus.FORBIDDEN),
    OKR_LINK_ERROR(HttpStatus.UNPROCESSABLE_ENTITY),
    WATERFALL_MODE_KPIS_CAN_ONLY_ASSIGNED_UNIT(HttpStatus.UNPROCESSABLE_ENTITY),
    DEADLINE_INVALID_FORMAT(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_PERMISSION_REPLACE_KPI(HttpStatus.FORBIDDEN),
    KPI_REPLACED_NO_LONGER_ACTIVE(HttpStatus.UNPROCESSABLE_ENTITY),
    KPI_REPLACEMENT_PENDING_APPROVAL(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_PERMISSION_EDIT_WEIGHT_KPI(HttpStatus.FORBIDDEN),
    CANNOT_CHANGE_WEIGHT_KPI_REPLACED_DEACTIVATED(HttpStatus.UNPROCESSABLE_ENTITY),

    // KpiCycleLockService
    LOCKING_RESULTS_ROOT_UNIT_ALSO_LOCKS_CYCLE(HttpStatus.CONFLICT),
    CYCLE_DATA_CHANGED_SINCE_CHECK(HttpStatus.CONFLICT),
    PERIOD_NOT_UNFINISHED_PERIOD_CYCLE(HttpStatus.UNPROCESSABLE_ENTITY),
    PERIOD_MORE_THAN_ONE_HANDLING_OPTION(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_HANDLING_OPTION_CHOSEN_PERIODS(HttpStatus.UNPROCESSABLE_ENTITY),
    ONLY_PERIODS_NOT_STARTED_CAN_CANCELLED(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_TARGET_CYCLE_CHOSEN_PERIOD(HttpStatus.UNPROCESSABLE_ENTITY),
    TARGET_CYCLE_MUST_DIFFERENT_CYCLE_BEING_LOCKED(HttpStatus.UNPROCESSABLE_ENTITY),
    TARGET_CYCLE_MUST_SAME_ORGANIZATION_SAME_CYCLE(HttpStatus.UNPROCESSABLE_ENTITY),
    TARGET_CYCLE_LOCKED(HttpStatus.UNPROCESSABLE_ENTITY),
    NEW_DATES_PERIOD_INVALID(HttpStatus.UNPROCESSABLE_ENTITY),
    DATES_PERIOD(HttpStatus.UNPROCESSABLE_ENTITY),
    CYCLE_LOCKED_2(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_PERMISSION_VIEW_EVALUATION_CYCLE(HttpStatus.FORBIDDEN),
    NO_PERMISSION_LOCK_EVALUATION_CYCLE(HttpStatus.FORBIDDEN),

    // KpiSubmissionService
    APPROVAL_RESULT_MUST_APPROVED_REJECTED(HttpStatus.UNPROCESSABLE_ENTITY),
    KPI_STOPPED(HttpStatus.UNPROCESSABLE_ENTITY),
    REPORTS_CAN_ONLY_SUBMITTED_KPIS_APPROVED_ADJUSTED(HttpStatus.UNPROCESSABLE_ENTITY),
    KPI_SPLIT_INTO_CHILD_KPIS(HttpStatus.UNPROCESSABLE_ENTITY),
    NOT_ASSIGNED_KPI(HttpStatus.FORBIDDEN),
    ENTER_ACTUAL_VALUE_QUANTITATIVE_KPIS(HttpStatus.UNPROCESSABLE_ENTITY),
    EVALUATION_PERIOD_NOT_STARTED(HttpStatus.UNPROCESSABLE_ENTITY),
    EVALUATION_PERIOD_ENDED(HttpStatus.UNPROCESSABLE_ENTITY),
    REPORT_START_DATE_CANNOT_BEFORE_START_DATE(HttpStatus.UNPROCESSABLE_ENTITY),
    REPORT_END_DATE_CANNOT_AFTER_END_DATE(HttpStatus.UNPROCESSABLE_ENTITY),
    END_DATE_CANNOT_BEFORE_START_DATE(HttpStatus.UNPROCESSABLE_ENTITY),
    SUBMITTED_FULL_NUMBER_REPORTS_KPI(HttpStatus.UNPROCESSABLE_ENTITY),
    SUBMITTED_REPORT_KPI_MONTH(HttpStatus.UNPROCESSABLE_ENTITY),
    MONTH_KPI_3_REPORTS_SUBMITTED_QUARTER_PERIOD(HttpStatus.UNPROCESSABLE_ENTITY),
    REPORT_PERIOD_OVERLAPS_PREVIOUS_SUBMISSION(HttpStatus.UNPROCESSABLE_ENTITY),
    INVALID_QUALITATIVE_EVALUATION_LEVEL(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_PERMISSION_EDIT_SUBMISSION(HttpStatus.FORBIDDEN),
    KPI_STOPPED_2(HttpStatus.UNPROCESSABLE_ENTITY),
    ONLY_SUBMISSIONS_DRAFT_REJECTED_STATUS_CAN_EDITED(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_PERMISSION_VIEW_SUBMISSION(HttpStatus.FORBIDDEN),
    NO_PERMISSION_APPROVE_UNIT_SUBMISSIONS(HttpStatus.FORBIDDEN),
    CANNOT_APPROVE_SUBMISSIONS_SOMEONE_EQUIVALENT_HIGHER_RANK(HttpStatus.FORBIDDEN),
    SUBMISSION_APPROVED_MANAGER_EQUIVALENT_HIGHER_LEVEL(HttpStatus.UNPROCESSABLE_ENTITY),
    ONLY_SUBMISSIONS_PENDING_APPROVAL_STATUS_CAN_DELETED(HttpStatus.UNPROCESSABLE_ENTITY),
    ONLY_SUBMITTER_MAY_DELETE_SUBMISSION(HttpStatus.FORBIDDEN),
    // Hoàn duyệt bài nộp (trả lại để làm lại)
    SUBMISSION_CANNOT_BE_RETURNED_IN_STATUS(HttpStatus.UNPROCESSABLE_ENTITY),
    SUBMISSION_RETURN_KPI_NOT_ACTIVE(HttpStatus.UNPROCESSABLE_ENTITY),
    SUBMISSION_RETURN_AFTER_EVALUATION_FINALIZED(HttpStatus.UNPROCESSABLE_ENTITY),
    RESUBMIT_DEADLINE_MUST_BE_IN_FUTURE(HttpStatus.UNPROCESSABLE_ENTITY),
    EVALUATION_BLOCKED_AWAITING_RESUBMISSION(HttpStatus.UNPROCESSABLE_ENTITY),

    // KpiWorkflowConfigService
    ACCOUNT_OUTSIDE_ORGANIZATION_KPI_FLOW_CANNOT_CONFIGURED(HttpStatus.UNPROCESSABLE_ENTITY),
    COULD_NOT_CONVERT_KPI_FLOW_CONFIGURATION_JSON(HttpStatus.UNPROCESSABLE_ENTITY),

    // LandingLeadService
    SENT_TOO_MANY_TIMES(HttpStatus.UNPROCESSABLE_ENTITY),

    // LarkAuthService
    ORGANIZATION_NOT_ENABLED_LARK_SIGN(HttpStatus.UNPROCESSABLE_ENTITY),
    COULD_NOT_GET_EMAIL_LARK(HttpStatus.UNPROCESSABLE_ENTITY),
    ORGANIZATION_NOT_VERIFIED_LINK_LARK(HttpStatus.UNPROCESSABLE_ENTITY),
    LARK_ACCOUNT_OUTSIDE(HttpStatus.UNPROCESSABLE_ENTITY),
    EMAIL_BELONGS_ANOTHER_ORGANIZATION_SYSTEM(HttpStatus.UNPROCESSABLE_ENTITY),
    ORGANIZATION_NOT_CONFIGURED_DEFAULT_UNIT_ROLE_USERS(HttpStatus.UNPROCESSABLE_ENTITY),

    // LarkCredentialResolver
    SHARED_LARK_APP_MODE_NOT_SUPPORTED(HttpStatus.UNPROCESSABLE_ENTITY),
    ORGANIZATION_NOT_CONFIGURED_LARK_APP_ID_APP(HttpStatus.UNPROCESSABLE_ENTITY),

    // LarkOAuthClient
    COULD_NOT_CONNECT_LARK(HttpStatus.UNPROCESSABLE_ENTITY),
    LARK_REJECTED_SIGN_REQUEST(HttpStatus.UNPROCESSABLE_ENTITY),
    LARK_DID_NOT_RETURN_ACCESS_TOKEN(HttpStatus.UNPROCESSABLE_ENTITY),
    COULD_NOT_GET_LARK_ACCOUNT_INFORMATION(HttpStatus.UNPROCESSABLE_ENTITY),
    LARK_DID_NOT_RETURN_USER_IDENTIFIER(HttpStatus.UNPROCESSABLE_ENTITY),

    // LarkSettingsService
    LARK_SIGN_COULD_NOT_ENABLED(HttpStatus.UNPROCESSABLE_ENTITY),
    LARK_DID_NOT_RETURN_ORGANIZATION_IDENTIFIER(HttpStatus.UNPROCESSABLE_ENTITY),
    LARK_ORGANIZATION_LINKED_COMPANY_SYSTEM(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_PERMISSION_ACCESS_ORGANIZATION_CONFIGURATION(HttpStatus.FORBIDDEN),
    CURRENT_USER_OUTSIDE_ORGANIZATION(HttpStatus.FORBIDDEN),
    DEFAULT_UNIT_MUST_BELONG_ORGANIZATION(HttpStatus.UNPROCESSABLE_ENTITY),
    DEFAULT_ROLE_MUST_BELONG_ORGANIZATION(HttpStatus.UNPROCESSABLE_ENTITY),

    // NotificationService
    CANNOT_MARK_SOMEONE_ELSE_NOTIFICATIONS_READ(HttpStatus.FORBIDDEN),

    // OAuthStateService
    INVALID_LARK_SIGN_SESSION(HttpStatus.UNPROCESSABLE_ENTITY),
    INVALID_LARK_CONNECTION_SESSION(HttpStatus.UNPROCESSABLE_ENTITY),
    LARK_SIGN_SESSION_EXPIRED_INVALID(HttpStatus.UNPROCESSABLE_ENTITY),

    // OkrService
    MISSING_REQUIRED_COLUMNS_2(HttpStatus.UNPROCESSABLE_ENTITY),
    FILE_PROCESSING_FAILED(HttpStatus.UNPROCESSABLE_ENTITY),

    // OrganizationService
    MAXIMUM_SCALE_MUST_MORE_SINCE_COMPLETING_100(HttpStatus.UNPROCESSABLE_ENTITY),
    LEVEL_CANNOT_DELETED_BECAUSE_UNITS_USING(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_IMAGE_FILE_SELECTED(HttpStatus.UNPROCESSABLE_ENTITY),
    FILE_MUST_IMAGE(HttpStatus.UNPROCESSABLE_ENTITY),
    IMAGE_MUST_NOT_EXCEED_5MB(HttpStatus.UNPROCESSABLE_ENTITY),
    INVALID_IMAGE_TYPE(HttpStatus.UNPROCESSABLE_ENTITY),

    // OrgCodeRuleService
    NO_RULES_WERE_SUBMITTED(HttpStatus.UNPROCESSABLE_ENTITY),
    MISSING_CODE_TYPE(HttpStatus.UNPROCESSABLE_ENTITY),
    ENTER_CODE(HttpStatus.UNPROCESSABLE_ENTITY),
    CODE_EXISTS_CODE_PATTERN_NO_SEQUENCE_FIELD(HttpStatus.UNPROCESSABLE_ENTITY),
    COULD_NOT_ISSUE_NEW_CODE_PATTERN(HttpStatus.UNPROCESSABLE_ENTITY),
    CODE_GENERATED_CHARACTERS_LONG_EXCEEDING_LIMIT(HttpStatus.UNPROCESSABLE_ENTITY),
    CODE_PATTERN_CANNOT_EMPTY(HttpStatus.UNPROCESSABLE_ENTITY),
    CODE_PATTERN_CAN_MOST_100_CHARACTERS(HttpStatus.UNPROCESSABLE_ENTITY),
    CODE_PATTERN_MUST_SEQUENCE_FIELD_EXAMPLE_3(HttpStatus.UNPROCESSABLE_ENTITY),
    CODE_PATTERN_MAY_ONLY_ONE_SEQUENCE_FIELD(HttpStatus.UNPROCESSABLE_ENTITY),
    SEQUENCE_FIELD_CAN_MOST_8_DIGITS(HttpStatus.UNPROCESSABLE_ENTITY),
    CODE_PATTERN_CONTAINS_UNSUPPORTED_TOKEN(HttpStatus.UNPROCESSABLE_ENTITY),
    TEXT_PART_CODE_PATTERN_MAY_ONLY_CONTAIN(HttpStatus.UNPROCESSABLE_ENTITY),
    TEXT_PART_CODE_PATTERN_MAY_ONLY_CONTAIN_UNDERSCORE(HttpStatus.UNPROCESSABLE_ENTITY),

    // OrgUnitDelegationService
    DELEGATE_NO_ROLE_ORGANIZATION(HttpStatus.UNPROCESSABLE_ENTITY),
    DELEGATION_CAN_ONLY_GIVEN_SOMEONE_WHO_HEAD(HttpStatus.UNPROCESSABLE_ENTITY),
    END_DATE_MUST_AFTER_START_DATE(HttpStatus.UNPROCESSABLE_ENTITY),
    END_DATE_PAST(HttpStatus.UNPROCESSABLE_ENTITY),
    UNIT_OUTSIDE_ORGANIZATION(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_PERMISSION_DELEGATE_MANAGEMENT_UNIT(HttpStatus.FORBIDDEN),
    PERSON_CAN_MANAGE_UNIT_THROUGH_ORGANIZATION_TREE(HttpStatus.UNPROCESSABLE_ENTITY),
    CANNOT_DELEGATE(HttpStatus.UNPROCESSABLE_ENTITY),
    PERSON_DELEGATED_MANAGEMENT_UNIT(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_PERMISSION_REVOKE_DELEGATIONS_UNIT(HttpStatus.FORBIDDEN),

    // OrgUnitService
    ORGANIZATION_LIMIT_HIERARCHY_LEVELS_REACHED(HttpStatus.UNPROCESSABLE_ENTITY),
    CANNOT_REMOVE_ROLE_BECAUSE_EMPLOYEES_UNIT_HOLD(HttpStatus.UNPROCESSABLE_ENTITY),
    UNIT_CANNOT_DELETED_BECAUSE_CHILD_UNITS(HttpStatus.UNPROCESSABLE_ENTITY),
    UNIT_CANNOT_DELETED_BECAUSE_ACTIVE_EMPLOYEES_POSITIONS(HttpStatus.UNPROCESSABLE_ENTITY),
    UNIT_CANNOT_MOVED_INTO_ITSELF(HttpStatus.UNPROCESSABLE_ENTITY),
    UNIT_CANNOT_MOVED_INTO_ONE_OWN_CHILD(HttpStatus.UNPROCESSABLE_ENTITY),
    MISSING_REQUIRED_COLUMNS_3(HttpStatus.UNPROCESSABLE_ENTITY),
    UNIT_NAME_REQUIRED(HttpStatus.UNPROCESSABLE_ENTITY),
    UNIT_CODE_REQUIRED(HttpStatus.UNPROCESSABLE_ENTITY),
    HIERARCHY_LEVEL_LIMIT_REACHED_UNIT(HttpStatus.UNPROCESSABLE_ENTITY),

    // PermissionService
    SOME_PERMISSIONS_WERE_NOT_FOUND(HttpStatus.NOT_FOUND),
    ROLE_PERMISSION_INFORMATION_NOT_FOUND(HttpStatus.NOT_FOUND),

    // PlatformRagController
    DOCUMENT_DOES_NOT_EXIST(HttpStatus.UNPROCESSABLE_ENTITY),

    // PointConversionService
    ORGANIZATION_NOT_ENABLED_WALLET_FEATURE(HttpStatus.UNPROCESSABLE_ENTITY),
    ORGANIZATION_NOT_ENABLED_REWARD_POINTS_MONEY_CANNOT(HttpStatus.UNPROCESSABLE_ENTITY),
    REQUEST_ID_USED_ANOTHER_CONVERSION(HttpStatus.UNPROCESSABLE_ENTITY),

    // PolicyService
    INVALID_EFFECT_VALUE(HttpStatus.UNPROCESSABLE_ENTITY),
    INVALID_CONDITION_TYPE(HttpStatus.UNPROCESSABLE_ENTITY),
    CONDITION_JSON_FORMAT_INVALID(HttpStatus.UNPROCESSABLE_ENTITY),
    POLICY_ASSIGNED_ROLE(HttpStatus.CONFLICT),
    LINK_BETWEEN_ROLE_POLICY_NOT_FOUND(HttpStatus.NOT_FOUND),

    // RagController
    QUESTION_CANNOT_EMPTY(HttpStatus.UNPROCESSABLE_ENTITY),
    KEYGO_GUIDE_LOADED_PLATFORM_ADMINISTRATOR_PLATFORM_ADMINISTRATION(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_PERMISSION_MANAGE_ORGANIZATION_DOCUMENTS(HttpStatus.FORBIDDEN),

    // RagIngestionService
    ONLY(HttpStatus.UNPROCESSABLE_ENTITY),

    // RefreshTokenService
    REFRESH_TOKEN_MISSING(HttpStatus.UNPROCESSABLE_ENTITY),
    REFRESH_TOKEN_INVALID_REVOKED(HttpStatus.UNPROCESSABLE_ENTITY),
    REFRESH_TOKEN_EXPIRED(HttpStatus.UNPROCESSABLE_ENTITY),

    // ReminderService
    PERSON_NO_EMAIL_CANNOT_SENT(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_PERMISSION_SEND_REMINDERS_PERSON(HttpStatus.FORBIDDEN),

    // ReportService
    DATA_SOURCE_CONNECTED_REPORT(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_PERMISSION_PIN_CHART(HttpStatus.UNPROCESSABLE_ENTITY),

    // RewardBudgetService
    PERSON_QUOTA_TIME_RANGE_OVERLAPS_ONE_CHOSE(HttpStatus.UNPROCESSABLE_ENTITY),
    CANNOT_LOWER_QUOTA_POINTS_BECAUSE_POINTS_USED(HttpStatus.UNPROCESSABLE_ENTITY),
    CANNOT_NARROW_VALIDITY_RANGE_QUOTA_USED_POINTS(HttpStatus.UNPROCESSABLE_ENTITY),
    NEW_TIME_RANGE_OVERLAPS_ANOTHER_QUOTA_PERSON(HttpStatus.UNPROCESSABLE_ENTITY),
    CANNOT_DELETE_QUOTA_BECAUSE_REWARD_PROPOSALS_COUNT(HttpStatus.UNPROCESSABLE_ENTITY),
    QUOTA_CAN_ATTACHED_CYCLE_PERIOD_NOT_BOTH(HttpStatus.UNPROCESSABLE_ENTITY),
    CHOOSE_CYCLE_PERIOD_ENTER_TIME_RANGE_QUOTA(HttpStatus.UNPROCESSABLE_ENTITY),
    END_DATE_MUST_AFTER_START_DATE_2(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_START_END_DATE_CANNOT_USED_BOUND(HttpStatus.UNPROCESSABLE_ENTITY),

    // RewardCertificateService
    TEMPLATE_NAMED_EXISTS_ORGANIZATION(HttpStatus.UNPROCESSABLE_ENTITY),

    // RewardCheckinService
    TWO_REWARD_MILESTONES_SET_DAY(HttpStatus.UNPROCESSABLE_ENTITY),
    REWARD_MILESTONE_DAY_OUTSIDE_DAY_CYCLE_NEVER(HttpStatus.UNPROCESSABLE_ENTITY),
    ORGANIZATION_NOT_ENABLED_REWARD_POINTS(HttpStatus.UNPROCESSABLE_ENTITY),
    ORGANIZATION_NOT_ENABLED_DAILY_CHECK(HttpStatus.UNPROCESSABLE_ENTITY),
    COMPANY_LEADERS_DO_NOT_NEED_CHECK(HttpStatus.UNPROCESSABLE_ENTITY),
    TODAY_DAY_OFF_CHECK_NOT_AVAILABLE(HttpStatus.UNPROCESSABLE_ENTITY),
    CHECKED_TODAY(HttpStatus.UNPROCESSABLE_ENTITY),
    COULD_NOT_READ_LIST_STREAK_REWARD_MILESTONES(HttpStatus.UNPROCESSABLE_ENTITY),

    // RewardGiftService
    STOCK_CANNOT_EDITED_WHILE_PENDING_REDEMPTION_REQUESTS(HttpStatus.UNPROCESSABLE_ENTITY),
    CANNOT_DELETE_BECAUSE_PENDING_REDEMPTION_REQUESTS(HttpStatus.UNPROCESSABLE_ENTITY),
    CANNOT_DELETE_BECAUSE_REDEMPTIONS_HISTORY(HttpStatus.UNPROCESSABLE_ENTITY),
    GIFT_OUTSIDE_ORGANIZATION(HttpStatus.UNPROCESSABLE_ENTITY),

    // RewardGrantService
    EACH_REWARD_CAN_GO_MOST_EMPLOYEES(HttpStatus.UNPROCESSABLE_ENTITY),
    LIST_DUPLICATE_EMPLOYEES(HttpStatus.UNPROCESSABLE_ENTITY),
    SOME_EMPLOYEES_LIST_NO_LONGER_EXIST_SYSTEM(HttpStatus.UNPROCESSABLE_ENTITY),
    EMPLOYEE_NO_LONGER_ACTIVE(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_PERMISSION_REWARD_POINTS_EMPLOYEE(HttpStatus.FORBIDDEN),
    NO_PERMISSION_REWARD_EMPLOYEE(HttpStatus.FORBIDDEN),
    ONLY_CREATOR_PROPOSAL_CAN_CANCEL(HttpStatus.FORBIDDEN),
    ONLY_APPROVED_PROPOSALS_WHOSE_POINTS_GRANTED_CAN(HttpStatus.UNPROCESSABLE_ENTITY),
    CANNOT_REVOKE_BECAUSE_FOLLOWING_EMPLOYEES_SPENT_POINTS(HttpStatus.UNPROCESSABLE_ENTITY),
    PROPOSAL_NO_LONGER_PENDING_APPROVAL(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_PERMISSION_APPROVE_REWARDS_UNIT(HttpStatus.FORBIDDEN),
    CANNOT_APPROVE_OWN_REWARD_PROPOSAL(HttpStatus.FORBIDDEN),
    CHOSEN_CERTIFICATE_TEMPLATE_NO_LONGER_EXISTS(HttpStatus.UNPROCESSABLE_ENTITY),
    CERTIFICATE_TEMPLATE_TURNED_OFF_CANNOT_USED_AWARDS(HttpStatus.UNPROCESSABLE_ENTITY),

    // RewardProgramRunService
    CHOOSE_CYCLE_PERIOD_RANK(HttpStatus.UNPROCESSABLE_ENTITY),
    REWARDS_CAN_ONLY_GRANTED_PREVIEW(HttpStatus.UNPROCESSABLE_ENTITY),
    RANKING_CHANGED_SINCE_PREVIEW(HttpStatus.UNPROCESSABLE_ENTITY),
    TOTAL_POINTS_GRANTED(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_ONE_ELIGIBLE_REWARDS_RUN(HttpStatus.UNPROCESSABLE_ENTITY),
    ONLY_RUNS_GRANTED_REWARDS_CAN_REVOKED(HttpStatus.UNPROCESSABLE_ENTITY),
    PROGRAM_GRANTED_REWARDS(HttpStatus.UNPROCESSABLE_ENTITY),
    RUN_OUTSIDE_ORGANIZATION(HttpStatus.UNPROCESSABLE_ENTITY),

    // RewardProgramService
    SCOPE_PROGRAM_GRANTED_REWARDS_BEFORE_CANNOT_CHANGED(HttpStatus.UNPROCESSABLE_ENTITY),
    CANNOT_DELETE_BECAUSE_ACTUALLY_GRANTED_REWARDS(HttpStatus.UNPROCESSABLE_ENTITY),
    RATING(HttpStatus.UNPROCESSABLE_ENTITY),
    COULD_NOT_READ_REWARD_TIER_CONFIGURATION(HttpStatus.UNPROCESSABLE_ENTITY),
    LEAST_ONE_REWARD_TIER_REQUIRED(HttpStatus.UNPROCESSABLE_ENTITY),
    REWARD_TIER_END_RANK(HttpStatus.UNPROCESSABLE_ENTITY),
    TWO_REWARD_TIERS_OVERLAP_RANK(HttpStatus.UNPROCESSABLE_ENTITY),
    REWARD_TIER_CONFIGURATION_PROGRAM_CORRUPTED(HttpStatus.UNPROCESSABLE_ENTITY),
    COULD_NOT_SAVE_REWARD_TIER_CONFIGURATION(HttpStatus.UNPROCESSABLE_ENTITY),
    PROGRAM_OUTSIDE_ORGANIZATION(HttpStatus.UNPROCESSABLE_ENTITY),

    // RewardQueryService
    NO_PERMISSION_VIEW_EMPLOYEE_REWARD_POINTS(HttpStatus.FORBIDDEN),

    // RewardRankingService
    PERIOD_PERFORMANCE_SCORE_METRIC_CAN_ONLY_USED(HttpStatus.UNPROCESSABLE_ENTITY),
    CYCLE_FINAL_SCORE_METRIC_CAN_ONLY_USED(HttpStatus.UNPROCESSABLE_ENTITY),

    // RewardRedemptionService
    ONLY_CREATOR_REQUEST_CAN_CANCEL(HttpStatus.FORBIDDEN),
    REQUEST_WAITING_CONFIRMATION_GIFT_PROVIDER_CANNOT_CANCELLED(HttpStatus.UNPROCESSABLE_ENTITY),
    GIFT_COULD_NOT_OBTAINED_PROVIDER(HttpStatus.UNPROCESSABLE_ENTITY),
    REQUEST_NO_LONGER_PENDING(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_PERMISSION_HANDLE_REDEMPTION_REQUESTS(HttpStatus.FORBIDDEN),

    // RewardRedemptionTx
    GIFT_CAN_NO_LONGER_REDEEMED(HttpStatus.UNPROCESSABLE_ENTITY),
    GIFT_OUT_STOCK_DOES_NOT_QUANTITY_CHOSE(HttpStatus.UNPROCESSABLE_ENTITY),
    REQUEST_NO_LONGER_AWAITING_DELIVERY(HttpStatus.UNPROCESSABLE_ENTITY),

    // RewardTool
    NO_PERMISSION_GRANT_REWARDS_NO_REWARD_BUDGET(HttpStatus.FORBIDDEN),

    // RewardWalletService
    INSUFFICIENT_POINT_BALANCE(HttpStatus.UNPROCESSABLE_ENTITY),

    // RoleService
    EACH_HIERARCHY_LEVEL_MAY_MOST_1(HttpStatus.UNPROCESSABLE_ENTITY),
    CANNOT_DELETE_SYSTEM_ROLE(HttpStatus.UNPROCESSABLE_ENTITY),
    CANNOT_DELETE_ROLE_BECAUSE_EMPLOYEES_ORGANIZATION_HOLD(HttpStatus.UNPROCESSABLE_ENTITY),

    // SepayReconcileService
    EVENT_HANDLED(HttpStatus.UNPROCESSABLE_ENTITY),
    EVENT_HANDLED_BY_SOMEONE_ELSE(HttpStatus.UNPROCESSABLE_ENTITY),
    CHOOSE_TOP_UP_ORDER_MATCH(HttpStatus.UNPROCESSABLE_ENTITY),
    ORDER_PAID(HttpStatus.UNPROCESSABLE_ENTITY),
    CHOOSE_PERSON_CREDIT(HttpStatus.UNPROCESSABLE_ENTITY),
    PERSON_CREDIT_OUTSIDE_ORGANIZATION(HttpStatus.UNPROCESSABLE_ENTITY),
    EVENT_NO_VALID_AMOUNT_CANNOT_CREDITED(HttpStatus.UNPROCESSABLE_ENTITY),

    // SidebarSettingService
    NO_PERMISSION_RENAME_ORGANIZATION_NAVIGATION_ITEMS(HttpStatus.FORBIDDEN),

    // StatsTierResolver
    NO_PERMISSION_VIEW_STATISTICS(HttpStatus.FORBIDDEN),
    COULD_NOT_IDENTIFY_CURRENT_USER(HttpStatus.FORBIDDEN),

    // TopupOrderService
    ORGANIZATION_NOT_CONFIGURED_RECEIVING_BANK_ACCOUNT(HttpStatus.UNPROCESSABLE_ENTITY),
    TOP_UP_AMOUNT_MUST_BETWEEN(HttpStatus.UNPROCESSABLE_ENTITY),
    TOP_UP_ORDERS_AWAITING_PAYMENT(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_PERMISSION_VIEW_TOP_UP_ORDER(HttpStatus.FORBIDDEN),
    NO_PERMISSION_CANCEL_TOP_UP_ORDER(HttpStatus.FORBIDDEN),
    ORDER_RECEIVED_MONEY_CANNOT_CANCELLED(HttpStatus.UNPROCESSABLE_ENTITY),
    ONLY_ORDERS_AWAITING_PAYMENT_CAN_CANCELLED(HttpStatus.UNPROCESSABLE_ENTITY),
    COULD_NOT_GENERATE_TOP_UP_ORDER_CODE(HttpStatus.UNPROCESSABLE_ENTITY),

    // TopupReceiptService
    NO_PERMISSION_VIEW_OTHER_PEOPLE_RECEIPTS(HttpStatus.FORBIDDEN),

    // UrboxCatalogService
    GIFT_CATALOG(HttpStatus.UNPROCESSABLE_ENTITY),
    GIFT_NOT_FOUND_URBOX_INVENTORY(HttpStatus.UNPROCESSABLE_ENTITY),
    COULD_NOT_DERIVE_POINT_PRICE_GIFT(HttpStatus.UNPROCESSABLE_ENTITY),

    // UrboxClient
    URBOX_CONNECTION_NOT_FULLY_CONFIGURED(HttpStatus.UNPROCESSABLE_ENTITY),
    COULD_NOT_SIGN_REQUEST_URBOX(HttpStatus.UNPROCESSABLE_ENTITY),
    URBOX_GIFT_INVENTORY_CONNECTION_NOT_ENABLED(HttpStatus.UNPROCESSABLE_ENTITY),
    URBOX_SERVER_RETURNED_HTTP_ERROR_WHILE_READING(HttpStatus.UNPROCESSABLE_ENTITY),
    URBOX_SERVER_RETURNED_HTTP_ERROR_WHILE_READING_NOT_FOUND(HttpStatus.UNPROCESSABLE_ENTITY),
    COULD_NOT_CONNECT_URBOX_GIFT_INVENTORY(HttpStatus.UNPROCESSABLE_ENTITY),
    URBOX_REPORTED_ERROR_WHILE_READING_GIFT_INVENTORY(HttpStatus.UNPROCESSABLE_ENTITY),

    // UserRoleService
    USER_ROLE_UNIT(HttpStatus.CONFLICT),
    USER_PERMISSION_INFORMATION_NOT_FOUND(HttpStatus.NOT_FOUND),

    // UserService
    EMAIL_EXISTS_SYSTEM(HttpStatus.CONFLICT),
    EMPLOYEE_CODE_USE(HttpStatus.UNPROCESSABLE_ENTITY),
    EMPLOYEE_CODE_USED_ANOTHER_PERSON(HttpStatus.UNPROCESSABLE_ENTITY),
    MISSING_REQUIRED_COLUMNS_4(HttpStatus.UNPROCESSABLE_ENTITY),
    UNIT(HttpStatus.UNPROCESSABLE_ENTITY),
    EMAIL_REQUIRED(HttpStatus.UNPROCESSABLE_ENTITY),
    FULL_NAME_REQUIRED(HttpStatus.UNPROCESSABLE_ENTITY),
    UNIT_CODE_DOES_NOT_EXIST(HttpStatus.UNPROCESSABLE_ENTITY),
    EMAIL_EXISTS_ACTIVE_SYSTEM(HttpStatus.UNPROCESSABLE_ENTITY),
    EMPLOYEE_CODE_USED_ANOTHER_PERSON_2(HttpStatus.UNPROCESSABLE_ENTITY),
    UNIT_DOES_NOT_EXIST(HttpStatus.UNPROCESSABLE_ENTITY),
    UNIT_ROLE(HttpStatus.UNPROCESSABLE_ENTITY),
    DEFAULT_EMPLOYEE_ROLE(HttpStatus.UNPROCESSABLE_ENTITY),
    ROLE_CODE(HttpStatus.UNPROCESSABLE_ENTITY),
    DEFAULT_EMPLOYEE_ROLE_NOT_FOUND(HttpStatus.UNPROCESSABLE_ENTITY),
    JOB_TITLE_DOES_NOT_EXIST_SYSTEM(HttpStatus.UNPROCESSABLE_ENTITY),
    UNIT_NO_MANAGER(HttpStatus.UNPROCESSABLE_ENTITY),
    CURRENT_USER_OUTSIDE_ORGANIZATION_2(HttpStatus.UNPROCESSABLE_ENTITY),

    // WorkflowConfigValidator
    INVALID_KPI_FLOW_CONFIGURATION(HttpStatus.UNPROCESSABLE_ENTITY),

    // WorkflowEngine
    ORGANIZATION_TURNED_OFF_STEP_KPI_FLOW_CONFIGURATION(HttpStatus.UNPROCESSABLE_ENTITY),
    ACTION_NOT_PART_ORGANIZATION_CURRENT_KPI_FLOW(HttpStatus.UNPROCESSABLE_ENTITY),
    // AnalyticsPeriodHelper
    KPI_PERIOD_NOT_FOUND(HttpStatus.UNPROCESSABLE_ENTITY),
    KPI_PERIOD_OUTSIDE_ORGANIZATION_2(HttpStatus.UNPROCESSABLE_ENTITY),

    // EmailService
    COULD_NOT_SEND_EMAIL(HttpStatus.UNPROCESSABLE_ENTITY),

    // EmailTemplateController
    NO_IMAGE_SELECTED_UPLOAD(HttpStatus.UNPROCESSABLE_ENTITY),
    ONLY_IMAGE_FILES_ACCEPTED(HttpStatus.UNPROCESSABLE_ENTITY),
    IMAGE_MUST_NOT_EXCEED_5MB_2(HttpStatus.UNPROCESSABLE_ENTITY),

    // EmailTemplateService
    NO_EMAIL_TYPE_CODE(HttpStatus.UNPROCESSABLE_ENTITY),
    CANNOT_TURNED_OFF(HttpStatus.UNPROCESSABLE_ENTITY),
    EMAIL_CONTENT_CANNOT_EMPTY(HttpStatus.UNPROCESSABLE_ENTITY),
    TEMPLATE_MUST_CONTAIN_VARIABLE(HttpStatus.UNPROCESSABLE_ENTITY),

    // EvaluationService
    NO_PERMISSION_VIEW_EVALUATION_BECAUSE_NOT_EMPLOYEE(HttpStatus.FORBIDDEN),

    // F360CampaignService
    NO_PERMISSION_VIEW_F360_CAMPAIGNS_2(HttpStatus.FORBIDDEN),
    CAMPAIGN_NOT_STARTED(HttpStatus.FORBIDDEN),

    // KpiCycleEvaluationService
    CYCLE_EVALUATION_UNIT_FINALIZED_SCORES_CANNOT_EDITED(HttpStatus.UNPROCESSABLE_ENTITY),
    CYCLE_FINAL_SCORE_MUST_BETWEEN_0(HttpStatus.UNPROCESSABLE_ENTITY),
    QUALITATIVE_LEVEL_MUST_BETWEEN_0_5(HttpStatus.UNPROCESSABLE_ENTITY),
    CALIBRATED_RATING_MUST_BETWEEN_1_5(HttpStatus.UNPROCESSABLE_ENTITY),
    UNIT_FINALIZED_CYCLE_SCORES_CANNOT_EDITED(HttpStatus.UNPROCESSABLE_ENTITY),
    PARENT_UNIT_FINALIZED_CYCLE(HttpStatus.UNPROCESSABLE_ENTITY),
    UNIT_SCORE_MUST_BETWEEN_0(HttpStatus.UNPROCESSABLE_ENTITY),
    ENTER_REASON_GIVING_UNIT_SCORE_DIFFERENT_MEMBERS(HttpStatus.UNPROCESSABLE_ENTITY),
    PARENT_UNIT_FINALIZED_CYCLE_2(HttpStatus.UNPROCESSABLE_ENTITY),
    RUN_FINALIZE_CYCLE_DATA_CHECK_BELL_CURVE(HttpStatus.UNPROCESSABLE_ENTITY),
    OUTSIDE_BELL_CURVE(HttpStatus.UNPROCESSABLE_ENTITY),
    PARENT_UNIT_FINALIZING_CYCLE(HttpStatus.UNPROCESSABLE_ENTITY),
    PARENT_UNIT_FINALIZED_CYCLE_DATA(HttpStatus.UNPROCESSABLE_ENTITY),
    UNIT_LOCKED_CYCLE_RESULTS(HttpStatus.UNPROCESSABLE_ENTITY),
    NO_PERMISSION_FINALIZE_UNLOCK_UNIT_CYCLE_EVALUATION(HttpStatus.FORBIDDEN),
    NO_PERMISSION_SEND_UNIT_CYCLE_EVALUATION_RESULTS(HttpStatus.FORBIDDEN),
    CHOOSE_LEAST_ONE_EMPLOYEE_SEND(HttpStatus.UNPROCESSABLE_ENTITY),

    // KpiCycleService
    COULD_NOT_DETERMINE_ORGANIZATION_EVALUATION_CYCLE(HttpStatus.UNPROCESSABLE_ENTITY),
    PERIOD_OUTSIDE_CYCLE_ORGANIZATION(HttpStatus.UNPROCESSABLE_ENTITY),
    DATES_PERIOD_MUST_WITHIN_DATES_CYCLE(HttpStatus.UNPROCESSABLE_ENTITY),
    ORGANIZATION_NOT_ENABLED_QUALITATIVE_KPIS_CYCLE_CAN(HttpStatus.UNPROCESSABLE_ENTITY),
    CYCLE_DATES_OVERLAP_CYCLE_SAME_TYPE(HttpStatus.UNPROCESSABLE_ENTITY),
    END_TIME_MUST_AFTER_START_TIME(HttpStatus.UNPROCESSABLE_ENTITY),

    // KpiPeriodService
    NOTIFICATION_TIME_MUST_BETWEEN_START_END_TIMES(HttpStatus.UNPROCESSABLE_ENTITY),
    PERIOD_KPIS_USE(HttpStatus.UNPROCESSABLE_ENTITY),
    PERIOD_DATES_MUST_WITHIN_DATES_CYCLE(HttpStatus.UNPROCESSABLE_ENTITY),

    // OrganizationService
    NUMBER_EVALUATION_REMINDER_DAYS_MUST_BETWEEN_0(HttpStatus.UNPROCESSABLE_ENTITY),
    DO_NOT_BELONG_ORGANIZATION_3(HttpStatus.FORBIDDEN),

    // OrgNotificationConfigService
    NO_PERMISSION_CHANGE_ORGANIZATION_NOTIFICATION_SETTINGS(HttpStatus.FORBIDDEN),

    // PermissionService
    NO_PERMISSION_EDIT_ROLE(HttpStatus.FORBIDDEN),
    PERMISSIONS_SYSTEM_ROLE_CANNOT_EDITED(HttpStatus.UNPROCESSABLE_ENTITY),

    // SidebarSettingController
    TOO_MANY_ITEMS_ONE_UPDATE(HttpStatus.UNPROCESSABLE_ENTITY),
    INVALID_KEY_LABEL(HttpStatus.UNPROCESSABLE_ENTITY),

    // StatsService
    NO_PERMISSION_VIEW_EMPLOYEE_PROGRESS(HttpStatus.FORBIDDEN),

    // SubmissionAttachmentService
    DOCUMENTS_CAN_ONLY_UPLOADED_REPORTS_PENDING_APPROVAL(HttpStatus.UNPROCESSABLE_ENTITY),
    DOCUMENTS_CAN_ONLY_DELETED_REPORTS_PENDING_APPROVAL(HttpStatus.UNPROCESSABLE_ENTITY),

    // UserRoleService
    NO_PERMISSION_ASSIGN_ROLES_UNIT(HttpStatus.FORBIDDEN),
    ROLE_MAY_NOT_ASSIGNED_UNIT(HttpStatus.UNPROCESSABLE_ENTITY),
    ALL_USERS_ROLE_UNIT(HttpStatus.UNPROCESSABLE_ENTITY),
    UNIT_NO_MANAGER_2(HttpStatus.UNPROCESSABLE_ENTITY),
    UNIT_SOMEONE_ROLE(HttpStatus.UNPROCESSABLE_ENTITY),

    // UserService
    NO_PERMISSION_VIEW_USER_INFORMATION(HttpStatus.FORBIDDEN),
    NO_PERMISSION_EDIT_USER(HttpStatus.FORBIDDEN),
    NO_PERMISSION_DELETE_USER(HttpStatus.FORBIDDEN),

    // DocumentService — thư viện tài liệu (docs/DOCUMENTS_DESIGN.md §7)
    DOCUMENT_NOT_FOUND(HttpStatus.NOT_FOUND),
    DOCUMENT_FORBIDDEN(HttpStatus.FORBIDDEN),
    DOCUMENT_FILE_TYPE_NOT_ALLOWED(HttpStatus.BAD_REQUEST),
    DOCUMENT_FILE_TOO_LARGE(HttpStatus.BAD_REQUEST),
    DOCUMENT_DUPLICATE(HttpStatus.CONFLICT),
    DOCUMENT_QUOTA_EXCEEDED(HttpStatus.UNPROCESSABLE_ENTITY),
    DOCUMENT_SCOPE_INVALID(HttpStatus.BAD_REQUEST),
    DOCUMENT_REINDEX_NOT_ALLOWED(HttpStatus.UNPROCESSABLE_ENTITY),
    DOCUMENT_LEGACY_READ_ONLY(HttpStatus.UNPROCESSABLE_ENTITY),
    DOCUMENT_PURGE_USER_ACTIVE(HttpStatus.UNPROCESSABLE_ENTITY),
    DOCUMENT_STORAGE_FAILED(HttpStatus.INTERNAL_SERVER_ERROR);

    private final HttpStatus status;

    ErrorCode(HttpStatus status) {
        this.status = status;
    }

    public HttpStatus status() {
        return status;
    }

    public String messageKey() {
        return "error." + name();
    }
}
