package com.kpitracking.service.email;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static com.kpitracking.service.email.EmailTemplateCatalog.alert;
import static com.kpitracking.service.email.EmailTemplateCatalog.button;
import static com.kpitracking.service.email.EmailTemplateCatalog.code;
import static com.kpitracking.service.email.EmailTemplateCatalog.info;

/**
 * Bản tiếng Anh của nội dung mặc định trong {@link EmailTemplateCatalog}. Thuật ngữ theo
 * {@code docs/i18n/GLOSSARY.md}.
 *
 * <p>Chỉ giữ phần chữ (nhãn, mô tả, tiêu đề, thân mail, mô tả biến); mã, nhóm, danh sách biến và biến
 * bắt buộc vẫn lấy từ bản gốc để hai ngôn ngữ không thể lệch nhau về cấu trúc. Loại mail nào thiếu ở
 * đây thì dùng bản tiếng Việt. Thêm ngôn ngữ thứ ba: thêm một lớp tương tự và nối vào
 * {@link EmailTemplateCatalog#localized}.
 */
final class EmailTemplateCatalogEn {

    private EmailTemplateCatalogEn() {}

    /** label, description, headerTitle, subject, body (body null ⇒ dùng mẫu thông báo chung). */
    record Text(String label, String description, String headerTitle, String subject, String body) {}

    static final Map<String, Text> TEXTS = new HashMap<>();

    static final Map<String, String> GROUPS = Map.of(
            EmailTemplateCatalog.GROUP_ACCOUNT, "Account & security",
            EmailTemplateCatalog.GROUP_KPI, "KPI notifications",
            EmailTemplateCatalog.GROUP_EVALUATION, "Evaluation",
            EmailTemplateCatalog.GROUP_WALLET, "Wallet & receipts");

    static final Map<String, String> VARIABLES = new HashMap<>();

    static final String NOTIFICATION_HEADER = "System notification";
    static final String NOTIFICATION_BODY = "<p>Hello <strong>{{ten_nguoi_nhan}}</strong>,</p>"
            + "<p>{{noi_dung}}</p>"
            + button("Open KeyGo", "{{link_he_thong}}");

    private static void put(String code, String label, String description, String header, String subject, String body) {
        TEXTS.put(code, new Text(label, description, header, subject, body));
    }

    private static void notification(String code, String label, String description) {
        TEXTS.put(code, new Text(label, description, NOTIFICATION_HEADER, "{{tieu_de}}", NOTIFICATION_BODY));
    }

    static {
        VARIABLES.put("ma_otp", "One-time code (OTP)");
        VARIABLES.put("email", "Recipient email");
        VARIABLES.put("ten_nguoi_nhan", "Recipient full name");
        VARIABLES.put("link_he_thong", "Link to the system");
        VARIABLES.put("mat_khau", "Issued password");
        VARIABLES.put("tieu_de", "Notification title generated by the system");
        VARIABLES.put("noi_dung", "Notification details generated by the system");
        VARIABLES.put("so_thong_bao", "Number of notifications combined");
        VARIABLES.put("khoang_thoi_gian", "Time range of the notifications");
        VARIABLES.put("danh_sach_thong_bao", "Notification list, grouped by event type");
        VARIABLES.put("so_bien_nhan", "Receipt number, e.g. PT2026/00000042");
        VARIABLES.put("so_tien", "Total amount received");
        VARIABLES.put("ma_don", "Top-up order code / transfer description");
        VARIABLES.put("bien_nhan", "Full receipt content generated by the system");
        VARIABLES.put("ten_nhan_vien", "Employee full name");
        VARIABLES.put("don_vi", "Employee's unit");
        VARIABLES.put("ky_danh_gia", "Evaluation cycle name");
        VARIABLES.put("diem_tu_danh_gia", "Self-assessment score");
        VARIABLES.put("diem_qltt", "Manager's score");
        VARIABLES.put("diem_chot", "Cycle final score");
        VARIABLES.put("xep_loai", "Rating label for the final score");
        VARIABLES.put("muc_dinh_tinh", "Qualitative level (0–5 scale)");
        VARIABLES.put("xep_loai_ma_tran", "Performance matrix rating (1–5)");
        VARIABLES.put("nhan_xet", "Reviewer's comment");
        VARIABLES.put("bang_diem_dot", "Score table for each period in the cycle");
        VARIABLES.put("nguoi_gui", "Sender full name");

        // ───────────────────────── Account & security ─────────────────────────
        put("auth_reset_password", "Password reset",
                "Sends an OTP when a user clicks forgot password.",
                "Account security", "Reset your password",
                "<p>Hello,</p>"
                + "<p>We recently received a request to <strong>reset the password</strong> for the account linked to this email address.</p>"
                + "<p>Your security code to reset your password is:</p>"
                + code("Security code", "{{ma_otp}}")
                + alert("danger", "This code is valid for 60 minutes only.")
                + "<p>If you did not make this request, please ignore this email to keep your account safe.</p>");

        put("auth_verify_email", "Email verification",
                "Sends an OTP to verify an email address.",
                "Confirm your email", "Confirm your KeyGo account",
                "<p>Welcome aboard,</p>"
                + "<p>To finish signing up and activate your KeyGo account, please use the OTP below:</p>"
                + code("Activation code", "{{ma_otp}}")
                + "<p>This code expires 24 hours after it was sent.</p>");

        put("auth_welcome_verify", "Welcome & verification",
                "Sent when a new organization signs up: a welcome message with a verification OTP.",
                "Welcome & verification", "Welcome to KeyGo - verify your account",
                "<p>Hello <strong>{{ten_nguoi_nhan}}</strong>,</p>"
                + "<p>Congratulations! Your company's profile and system data have been set up on KeyGo.</p>"
                + "<p>To get started, please verify your account with the OTP below:</p>"
                + code("Verification code", "{{ma_otp}}")
                + "<p>After verifying, you can sign in to manage KPIs and give your team access.</p>");

        put("auth_welcome", "Welcome",
                "Sent after the organization account has been activated.",
                "Welcome aboard", "Welcome to KeyGo",
                "<p>Hello <strong>{{ten_nguoi_nhan}}</strong>,</p>"
                + "<p>Congratulations! Your company's profile and system data have been set up on KeyGo.</p>"
                + "<p>You now have full access to <strong>manage workflows</strong>, "
                + "<strong>empower your team</strong> and <strong>measure results</strong> in real time.</p>"
                + button("Open KeyGo", "{{link_he_thong}}")
                + "<p>Best regards,<br><strong>The KeyGo team</strong></p>");

        put("auth_account_details", "Account details",
                "Sends sign-in details when an administrator creates an account for an employee.",
                "Your account", "Your KeyGo sign-in details",
                "<p>Hello <strong>{{ten_nguoi_nhan}}</strong>,</p>"
                + "<p>Your account has been created on KeyGo. "
                + "Here are your personal sign-in details:</p>"
                + info("Email", "{{email}}", "Password", "{{mat_khau}}")
                + button("Sign in now", "{{link_he_thong}}/login")
                + alert("warning", "For your security, change your password right after you first sign in."));

        // ───────────────────────── KPI notifications ─────────────────────────
        notification("kpi_submitted", "KPI submitted", "When an employee submits a KPI.");
        notification("kpi_assigned", "KPI assigned", "When a KPI is assigned to an employee.");
        notification("kpi_approved", "KPI approved", "When a KPI is approved.");
        notification("kpi_rejected", "KPI rejected", "When a KPI is rejected.");
        notification("kpi_approval_reminder", "Overdue KPI approval reminder",
                "When a KPI or adjustment approval step has waited longer than the configured number of days, or an admin needs to reassign the approver.");
        notification("kpi_approval_reverted", "KPI approval reverted", "When the approval of a KPI is reverted.");
        notification("submission_submitted", "KPI report needs review", "When an employee submits a result report for a KPI.");
        notification("submission_reviewed", "KPI report reviewed", "When a manager reviews a result report.");
        notification("submission_returned", "KPI report returned for rework",
                "When a reviewer returns a submission so the employee resubmits before the deadline.");
        notification("submission_escalated", "Report approved at the lower level",
                "Sent to the next level up AFTER the direct reviewer has accepted the report.");
        notification("reminder_deadline", "Submission deadline reminder", "Automatic reminder when a report deadline is near.");

        notification("bsc_scorecard_submitted", "BSC scorecard needs approval", "When a unit submits its BSC scorecard to the level above.");
        notification("bsc_scorecard_approved", "BSC scorecard approved", "When the level above approves the unit's BSC scorecard.");
        notification("bsc_scorecard_rejected", "BSC scorecard returned", "When the level above returns the BSC scorecard to the unit for changes, with a reason.");
        notification("bsc_scorecard_activated", "BSC scorecard applied", "When a BSC scorecard starts being used for scoring.");
        notification("bsc_scorecard_locked", "BSC scorecard locked/unlocked", "When a BSC scorecard is locked or unlocked for editing.");
        notification("bsc_cascaded", "BSC KPI assigned", "When the level above cascades a BSC KPI down to a unit.");
        notification("bsc_unit_result_finalized", "Period BSC results finalized", "When a unit's BSC results for a period are finalized.");
        notification("bsc_score_overridden", "BSC score overridden", "When an individual's BSC score is adjusted manually or the override is removed.");

        notification("ai_criteria_change_requested", "AI scoring rules change request",
                "When a lower unit requests changing the AI scoring rules you applied (for the applier / superior).");
        notification("ai_criteria_change_decided", "AI scoring rules request decided",
                "When your request to change the AI scoring rules is approved or rejected.");

        notification("reward_grant_submitted", "Reward proposal needs approval", "When a reward proposal above the quota is submitted (for the nearest approver).");
        notification("reward_grant_approved", "Reward proposal approved", "When the level above approves the grantor's reward proposal.");
        notification("reward_grant_rejected", "Reward proposal rejected", "When the level above rejects a reward proposal, with a note.");
        notification("reward_grant_cancelled", "Reward proposal withdrawn", "When the grantor withdraws a pending proposal (for the approver).");
        notification("reward_points_received", "Reward points received", "When reward points arrive in an employee's wallet.");
        notification("reward_grant_revoked", "Reward revoked", "When a granted reward is revoked and the points are deducted.");
        notification("reward_budget_assigned", "Reward quota", "When a manager is granted or adjusted a reward quota.");
        notification("reward_program_issued", "Program reward", "When an automatic reward program grants points to top-ranked people.");
        notification("reward_program_reverted", "Program reward revoked", "When a reward run of a program is revoked.");
        notification("reward_redemption_created", "New gift redemption request", "When an employee redeems points for a gift (for the gift team).");
        notification("reward_redemption_approved", "Gift redemption approved", "When a gift redemption request is approved and being prepared.");
        notification("reward_redemption_rejected", "Gift redemption rejected", "When a gift redemption request is rejected and the points are refunded.");
        notification("reward_redemption_delivered", "Gift delivered", "When the gift has been delivered or the gift code issued.");
        notification("reward_redemption_failed", "Gift issuing failed", "When the provider could not issue the gift; the points were refunded.");
        notification("reward_redemption_cancelled", "Gift redemption cancelled", "When the requester cancels their own request (for the gift team).");

        notification("wallet_topup_paid", "Top-up successful", "When the transfer has arrived and the wallet balance is credited.");
        notification("wallet_topup_expired", "Top-up order expired", "When a top-up order passes its validity time without payment.");
        notification("wallet_topup_unmatched", "Incoming payment not credited", "When money arrives but matches no order (for people with reconciliation permission).");
        notification("wallet_converted", "Converted to points", "When a user converts wallet balance into reward points.");

        notification("cycle_locked", "Evaluation cycle locked", "In-app notice to related people when a cycle is locked (no email).");
        notification("cycle_kpi_affected", "KPIs moved or closed by the cycle lock",
                "When locking a cycle moves an employee's KPIs to another cycle or closes them without scoring — sent to assignees and unit heads.");

        notification("f360_rate_request", "360 feedback invitation", "When someone is invited to fill in a 360 feedback form, or a submitted form is reopened for editing.");
        notification("f360_reminder", "360 feedback deadline reminder", "Reminds raters with unfinished 360 forms when the campaign is about to end.");
        notification("f360_report_released", "360 report published", "When a person's 360 feedback results are published to them.");
        notification("f360_nomination", "360 rater nomination", "When a 360 campaign opens nominations for reviewees, or a nomination needs approval.");
        notification("f360_declined", "360 rater declined", "Tells the approver and campaign creator when a rater declines a form, so they can replace the rater.");

        put("notification_digest", "Notification digest",
                "Sent when a person has several notifications at once — all combined into one email.",
                "Notification summary", "You have {{so_thong_bao}} new notifications from KeyGo",
                "<p>Hello <strong>{{ten_nguoi_nhan}}</strong>,</p>"
                + "<p>You have <strong>{{so_thong_bao}}</strong> new notifications in the period "
                + "{{khoang_thoi_gian}}:</p>"
                + "{{danh_sach_thong_bao}}"
                + button("Open KeyGo", "{{link_he_thong}}"));

        put("wallet_topup_receipt", "Top-up receipt",
                "Payment receipt sent to the payer after each successful wallet top-up. "
                + "The receipt body is generated by the system and cannot be edited.",
                "Payment receipt", "Payment receipt {{so_bien_nhan}} — {{so_tien}}",
                "<p>Hello <strong>{{ten_nguoi_nhan}}</strong>,</p>"
                + "<p>We confirm that we have received <strong>{{so_tien}}</strong> from top-up order "
                + "<strong>{{ma_don}}</strong>. Your wallet balance has been credited with this amount.</p>"
                + "<p>The payment receipt for this amount:</p>"
                + "{{bien_nhan}}"
                + "<p style=\"margin-top:16px;\">Please keep this email for your records.</p>"
                + button("View my wallet", "{{link_he_thong}}"));

        put("cycle_evaluation_result", "Cycle evaluation result",
                "Sends employees their overall evaluation result for a cycle.",
                "Cycle evaluation result", "Your evaluation result for {{ky_danh_gia}}",
                "<p>Hello <strong>{{ten_nhan_vien}}</strong>,</p>"
                + "<p>Your evaluation for <strong>{{ky_danh_gia}}</strong> in unit "
                + "<strong>{{don_vi}}</strong> has been finalized. Here is a summary of your scores:</p>"
                + info(
                        "Self-assessment score", "{{diem_tu_danh_gia}}",
                        "Manager's score", "{{diem_qltt}}",
                        "Cycle final score", "{{diem_chot}} — rating {{xep_loai}}",
                        "Qualitative level", "{{muc_dinh_tinh}}",
                        "Matrix rating", "{{xep_loai_ma_tran}}")
                + "<h2>Score details for each period in the cycle</h2>"
                + "<p>{{bang_diem_dot}}</p>"
                + "<p><strong>Comment:</strong> {{nhan_xet}}</p>"
                + "<p>Your detailed score sheet is attached to this email as an Excel file.</p>"
                + "<p>If you have questions about the result, please contact your manager directly.</p>"
                + "<p>Best regards,<br><strong>{{nguoi_gui}}</strong></p>");
    }

    /** Để kiểm tra đủ bản dịch trong test. */
    static List<String> codes() {
        return List.copyOf(TEXTS.keySet());
    }
}
