package com.kpitracking.enums;

/** Các loại thay đổi được ghi vào lịch sử công việc. */
public enum KpiTaskEventAction {
    CREATED, UPDATED, STATUS_CHANGED, DUE_CHANGED, VISIBILITY_CHANGED, KPI_MOVED, DELETED,
    ASSIGNED, REASSIGNED, FOLLOWER_ADDED, FOLLOWER_REMOVED, SUBTASK_ADDED, RECURRENCE_CHANGED, RECURRED,
    REMINDERS_CHANGED, PRIORITY_CHANGED, TITLE_CHANGED, DUPLICATED
}
